export const ACHIEVEMENTS = [
  {
    id: "first_workout",
    title: "First Hunt",
    description: "Complete your first workout",
    category: "milestone",
    icon: "🦖",
    target: 1,
  },
  {
    id: "week_streak",
    title: "7 Day Streak",
    description: "Train for 7 consecutive days",
    category: "consistency",
    icon: "🔥",
    target: 7,
  },
  {
    id: "month_streak",
    title: "Month Warrior",
    description: "Train for 30 consecutive days",
    category: "consistency",
    icon: "⚡",
    target: 30,
  },
  {
    id: "si_100",
    title: "Century Club",
    description: "Reach 100 Strength Index",
    category: "strength",
    icon: "💯",
    target: 100,
  },
  {
    id: "si_150",
    title: "Elite Tier",
    description: "Reach 150 Strength Index",
    category: "strength",
    icon: "👑",
    target: 150,
  },
  {
    id: "si_200",
    title: "Apex Predator",
    description: "Reach 200 Strength Index",
    category: "strength",
    icon: "🦅",
    target: 200,
  },
  {
    id: "volume_10k",
    title: "Iron Mover",
    description: "Lift 10,000kg total volume in a week",
    category: "volume",
    icon: "🏋️",
    target: 10000,
  },
  {
    id: "volume_25k",
    title: "Volume Beast",
    description: "Lift 25,000kg total volume in a week",
    category: "volume",
    icon: "💪",
    target: 25000,
  },
  {
    id: "workouts_50",
    title: "Committed",
    description: "Complete 50 workouts",
    category: "milestone",
    icon: "🎯",
    target: 50,
  },
  {
    id: "workouts_100",
    title: "Dedicated",
    description: "Complete 100 workouts",
    category: "milestone",
    icon: "🏆",
    target: 100,
  },
  {
    id: "social_first_follow",
    title: "Pack Member",
    description: "Follow your first athlete",
    category: "social",
    icon: "🤝",
    target: 1,
  },
  {
    id: "social_10_followers",
    title: "Growing Pack",
    description: "Gain 10 followers",
    category: "social",
    icon: "👥",
    target: 10,
  },
];
