/**
 * Popular exercises database organized by muscle group
 */

export const MUSCLE_GROUP_EXERCISES = {
  chest: [
    'Barbell Bench Press',
    'Incline Barbell Bench Press',
    'Dumbbell Bench Press',
    'Incline Dumbbell Bench Press',
    'Decline Bench Press',
    'Dumbbell Flyes',
    'Cable Chest Flyes',
    'Pec Deck Machine',
    'Push-Ups',
    'Chest Dips',
    'Chest Press Machine',
    'Incline Cable Flyes',
  ],
  back: [
    'Barbell Deadlift',
    'Barbell Row',
    'Pendlay Row',
    'T-Bar Row',
    'Dumbbell Row',
    'Lat Pulldown',
    'Pull-Ups',
    'Chin-Ups',
    'Seated Cable Row',
    'Face Pulls',
    'Back Extensions',
    'Rack Pulls',
  ],
  legs: [
    'Barbell Squat',
    'Front Squat',
    'Romanian Deadlift',
    'Leg Press',
    'Bulgarian Split Squat',
    'Walking Lunges',
    'Leg Extension',
    'Leg Curl',
    'Calf Raises',
    'Hack Squat',
    'Goblet Squat',
    'Hip Thrust',
  ],
  shoulders: [
    'Overhead Press',
    'Military Press',
    'Dumbbell Shoulder Press',
    'Lateral Raises',
    'Front Raises',
    'Rear Delt Flyes',
    'Face Pulls',
    'Arnold Press',
    'Cable Lateral Raises',
    'Upright Row',
    'Shrugs',
    'Machine Shoulder Press',
  ],
  arms: [
    'Barbell Curl',
    'Dumbbell Curl',
    'Hammer Curl',
    'Preacher Curl',
    'Cable Curl',
    'Close-Grip Bench Press',
    'Tricep Dips',
    'Skull Crushers',
    'Overhead Tricep Extension',
    'Tricep Pushdown',
    'Concentration Curl',
    'Cable Tricep Extension',
  ],
};

export const MUSCLE_GROUP_COLORS = {
  chest: {
    bg: 'from-primary/20 to-primary/5',
    text: 'text-primary',
    border: 'border-primary/30',
    glow: 'shadow-primary/20',
  },
  back: {
    bg: 'from-positive/20 to-positive/5',
    text: 'text-positive',
    border: 'border-positive/30',
    glow: 'shadow-positive/20',
  },
  legs: {
    bg: 'from-warning/20 to-warning/5',
    text: 'text-warning',
    border: 'border-warning/30',
    glow: 'shadow-warning/20',
  },
  shoulders: {
    bg: 'from-accent/20 to-accent/5',
    text: 'text-accent',
    border: 'border-accent/30',
    glow: 'shadow-accent/20',
  },
  arms: {
    bg: 'from-blue-500/20 to-blue-500/5',
    text: 'text-blue-400',
    border: 'border-blue-500/30',
    glow: 'shadow-blue-500/20',
  },
};
